name: list_app

packages:
  - apps/**
  - packages/**

command:
  bootstrap:
    environment:
      sdk: '>=3.3.0 <4.0.0'
      flutter: '>=3.3.0 <4.0.0'
    dependencies:
      cupertino_icons: ^1.0.6
    dev_dependencies:
      flutter_lints: ^3.0.1
