name: list_app

packages:
  - apps/**
  - packages/**

command:
  bootstrap:
    environment:
      sdk: '>=3.3.0 <4.0.0'
      flutter: '>=3.3.0 <4.0.0'
    dependencies:
      cupertino_icons: ^1.0.6
    dev_dependencies:
      flutter_lints: ^3.0.1

scripts:
  gen:
    run: |
      melos exec -c 1 -- "dart run build_runner build --delete-conflicting-outputs"
    description: Run build_runner.
    packageFilters:
      dependsOn: 'build_runner'
