name: list_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '3.5.4'
  flutter: "3.24.4"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  go_router: 13.2.5
  flutter_riverpod: 2.6.1
  flutter_dotenv: 5.2.1
  http: 1.2.2
  flutter_hooks: 0.20.5
  riverpod_annotation: 2.6.1
  riverpod_generator: 2.6.1
  hooks_riverpod: 2.5.1

  core_model:
    path: ../../packages/core/model

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.2
  freezed: 2.5.7
  build_runner: 2.4.8
  go_router_builder: 2.4.1

flutter:
  uses-material-design: true
