name: list_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^13.2.0
  flutter_riverpod: ^2.5.1
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5
  riverpod_generator: ^2.4.0
  hooks_riverpod: 2.5.1

  core_model:
    path: ../../packages/core/model

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  freezed: ^2.4.7

flutter:
  uses-material-design: true
